"""alter company_id in operations not nullable

Revision ID: a6ba80711d02
Revises: 4a01858f2c27
Create Date: 2023-06-01 16:32:03.704962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6ba80711d02'
down_revision = '4a01858f2c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('company_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_operations_company_id_companies'),
            'companies',
            ['company_id'],
            ['id'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f('fk_operations_company_id_companies'),
            type_='foreignkey',
        )
        batch_op.alter_column('company_id', existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
