"""add company table

Revision ID: 72e61604b5ce
Revises: e21d0fa15ff1
Create Date: 2023-05-17 16:15:37.924481

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72e61604b5ce'
down_revision = 'e21d0fa15ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'companies',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_id'],
            ['users.chat_id'],
            name=op.f('fk_companies_creator_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table(
        'companies_users',
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column(
            'join_date',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['chat_id'],
            ['users.chat_id'],
            name=op.f('fk_companies_users_chat_id_users'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['companies.id'],
            name=op.f('fk_companies_users_company_id_companies'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('chat_id', 'company_id', name=op.f('pk_companies_users')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies_users')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
