"""add company_id to operations table

Revision ID: 4a01858f2c27
Revises: 72e61604b5ce
Create Date: 2023-06-01 16:30:49.090268

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a01858f2c27'
down_revision = '72e61604b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
    connection = op.get_bind()
    user_id = connection.execute(
        """
        SELECT chat_id FROM users ORDER BY created_at LIMIT 1
        """,
    ).fetchone()[0]
    if user_id:
        company_id = connection.execute(
            """
            INSERT INTO companies (name, creator_id) VALUES ('Default', :user_id) RETURNING id
            """,
            user_id=user_id,
        ).fetchone()[0]
        all_user_chat_ids = connection.execute(
            """
            SELECT chat_id FROM users
            """,
        ).fetchall()
        # add all users to companies_users
        for user_chat_id in all_user_chat_ids:
            connection.execute(
                """
                INSERT INTO companies_users (chat_id, company_id) VALUES (:chat_id, :company_id)
                """,
                chat_id=user_chat_id[0],
                company_id=company_id,
            )
        connection.execute(
            """
            UPDATE operations SET company_id = :company_id
            """,
            company_id=company_id,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
