"""add failed operation

Revision ID: 2d7b5415848a
Revises: a6ba80711d02
Create Date: 2023-09-19 20:16:44.473538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d7b5415848a"
down_revision = "a6ba80711d02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operation_text", sa.String(), nullable=False),
        sa.Column("internal_event_id", sa.String(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.chat_id"],
            name=op.f("fk_failed_operations_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failed_operations")),
    )
    with op.batch_alter_table("failed_operations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_failed_operations_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("failed_operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failed_operations_id"))

    op.drop_table("failed_operations")
    # ### end Alembic commands ###
