"""add monobank_key to companies_users

Revision ID: 5b469522b1db
Revises: 2d7b5415848a
Create Date: 2024-09-17 20:56:13.294736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b469522b1db"
down_revision = "2d7b5415848a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("monobank_integration_key", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies_users", schema=None) as batch_op:
        batch_op.drop_column("monobank_integration_key")

    # ### end Alembic commands ###
