"""add unique contraint to monobank_accounts

Revision ID: 8c865a5e0996
Revises: af452ea528bd
Create Date: 2024-09-20 21:45:49.785230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c865a5e0996"
down_revision = "af452ea528bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monobank_accounts", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_monobank_accounts_id_chat_id_company_id", ["id", "chat_id", "company_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monobank_accounts", schema=None) as batch_op:
        batch_op.drop_constraint("uq_monobank_accounts_id_chat_id_company_id", type_="unique")

    # ### end Alembic commands ###
