"""remove mono integration key from us_cp

Revision ID: b404db959827
Revises: 018230e2dad3
Create Date: 2024-09-20 22:45:10.617175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b404db959827"
down_revision = "018230e2dad3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies_users", schema=None) as batch_op:
        batch_op.drop_column("monobank_integration_key")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("monobank_integration_key", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
