"""add monobank_integrations

Revision ID: 018230e2dad3
Revises: 8c865a5e0996
Create Date: 2024-09-20 22:44:46.080795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "018230e2dad3"
down_revision = "8c865a5e0996"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monobank_integrations",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("integration_key", sa.String(), nullable=True),
        sa.Column("webhook_secret", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["users.chat_id"],
            name=op.f("fk_monobank_integrations_chat_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_monobank_integrations_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chat_id", "company_id", name=op.f("pk_monobank_integrations")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monobank_integrations")
    # ### end Alembic commands ###
