"""empty message

Revision ID: 05ff3a3910bb
Revises: 9b8917a2fef2
Create Date: 2022-03-26 23:01:36.743201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ff3a3910bb'
down_revision = '9b8917a2fef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('is_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'is_approved')
    # ### end Alembic commands ###
