"""empty message

Revision ID: 9b8917a2fef2
Revises: 44811e788811
Create Date: 2022-03-26 22:10:27.714633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b8917a2fef2'
down_revision = '44811e788811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('repeat_type', sa.String(), nullable=True))
    op.add_column('operations', sa.Column('repeat_days', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'repeat_days')
    op.drop_column('operations', 'repeat_type')
    # ### end Alembic commands ###
