"""empty message

Revision ID: 96312b44ebce
Revises: 8bb6d1327f0d
Create Date: 2022-03-29 22:19:00.770251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96312b44ebce'
down_revision = '8bb6d1327f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ccy', sa.String(), nullable=False),
    sa.Column('base_ccy', sa.String(), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sale', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
