"""empty message

Revision ID: 8bb6d1327f0d
Revises: ba36df14a041
Create Date: 2022-03-27 21:10:19.371482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb6d1327f0d'
down_revision = 'ba36df14a041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('received_amount', sa.Integer(), nullable=True))
    op.add_column('operations', sa.Column('is_regular_operation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'is_regular_operation')
    op.drop_column('operations', 'received_amount')
    # ### end Alembic commands ###
