"""empty message

Revision ID: ba36df14a041
Revises: 05ff3a3910bb
Create Date: 2022-03-27 19:00:08.021769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba36df14a041'
down_revision = '05ff3a3910bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'currency')
    # ### end Alembic commands ###
